runtime: nodejs10

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

env_variables:
  DADDY_WHOAMI: "d.a.d.d.y on google app engine"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
