version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i --ci
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run compile
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate to Google Cloud Platform
          command: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run:
          name: Deploy
          command: gcloud app deploy --project=${GCLOUD_PROJECT_ID} --quiet
workflows:
  version: 2
  default:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - deploy:
          requires:
            - build
